### ISSUE TITLE
Style sheets

### ISSUE THREAD

**Issue by MrBrain295** [SideflipSaga/SideflipSaga.github.io#1]
Maybe you could add a CSS style sheet.
`<style type="text/css">body {
background-color: navy;
font-family: sans-serif;
margin-left: auto;
margin-right: auto;
max-width: 1080px;
min-wibody {dth: 256px;
padding-top: 8px;
padding-bottom: 24px;
padding-left: 24px;
padding-right: 24px;
}</style>` Like this (this is made for firefox)

**Comment by CasualSideo** [comment]
ok, @MrBrain295 this is my account and i'm locked out. i think you know that tho
